apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-flask
  labels:
    app: api-flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-flask
  template:
    metadata:
      labels:
        app: api-flask
    spec:
      containers:
      - name: api-flask
        image: seu_usuario/seu_repositorio:latest  # Substitua pelo seu repositório de imagem
        ports:
        - containerPort: 5000  # Porta onde sua aplicação Flask está rodando
        env:
        - name: ENVIRONMENT
          value: "production"  # Exemplo de variável de ambiente
---
apiVersion: v1
kind: Service
metadata:
  name: api-flask-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: api-flask
