name: Teste antes do Merge

on:
  pull_request:
    branches:
      - main  # Ou o branch que você deseja proteger
  push:
    branches:
      - main  # Ou o branch que você deseja proteger

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar Python (ou outra linguagem)
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Altere para a versão que você usa

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt
          pytest